name: share-text # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Amazing share text app between Android & Linux # 79 char long summary
description: |
  This is a messenger app between Android & Linux using Server|Client. You can share messages with your Android device easily and fastly

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  share-text:
    command: /usr/lib/jvm/jdk1.8.0_221/jre/bin/java -jar $SNAP/src/ShareText_Desktop.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      CLASSPATH: $SNAP/jar/ShareText_Desktop.jar
      PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
parts:
  share-text:
    source: .
    plugin: dump
    stage-packages: [openjdk-8-jre, openjdk-8-demo]
