name: share-text # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Amazing share text app between Android & Linux # 79 char long summary
description: |
  This is a messenger app between Android & Linux using Server|Client. You can share messages with your Android device easily and fastly

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  share-text:
    # See 'snapcraft plugins'
    source: .
    plugin: autotools

apps:
  share-text:
    extensions:
      - gnome-3-28
    command: sharetext-$SNAPCRAFT_PROJECT_VERSION/share_text.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - cups-control

parts:
  share-text:
    plugin: gradle
    source: https://github.com/AgelousisDev/ShareTextDesktop.git
    source-tag: WIP/ShareTextDesktop/develop
    gradle-output-dir: BIN
    gradle-options: [binZip, -xtest, -xcreateGitTag]
    override-build: |
      snapcraftctl build
      unzip -o DIST/sharetext_bin-*.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip
